# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Functions
connect_to_pgcli() {
    cat ~/.pgpass
    ssh -fN -L 3333:localhost:5432 ok-psql
    pgcli  -U oknesset -h localhost -p 3333 oknesset
}

i3log () {
	$@ `find ~/log/ | sort | tail -n 1`
}

# Aliases
## Git
alias gdt='git difftool'
alias glog="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"


alias shosts="cat ~/.ssh/config | grep 'Host '"
alias pgok=connect_to_pgcli
alias jn='nohup jupyter-notebook --notebook-dir=/home/noam/Dropbox/code/jupyter-notebooks 1>/dev/null &'
alias gdi='git icdiff'
alias szsh='source $HOME/.zshrc'
alias sconf='vim ~/.ssh/config'
alias ssh-genconf='cat ~/.ssh/configs/* > ~/.ssh/config'
alias ip-location='http -b ipinfo.io'
alias vim=nvim

alias setclip='xclip -selection c'
alias getclip='xclip -selection clipboard -o'
alias mkvirtualenv3='mkvirtualenv -p /usr/bin/python3'
alias pip-hack='/home/noam/.virtualenvs/csf/bin/python /home/noam/.virtualenvs/csf/bin/pip install'
alias i3log-less='i3log less'
alias i3log-tail='i3log tail -f'
alias ppath="python -c 'import sys; print(sys.path)'"
alias alg="alias | grep"


# Exports
export EDITOR=nvim
export SYSTEMD_EDITOR=nvim
export VISUAL=nvim
export CDPATH=.:~:~/projects/cloudlock/:~/projects/
export QT_GRAPHICSSYSTEM=native
export PATH=/home/noam/.gem/ruby/2.3.0/bin:$PATH
export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
export XDG_CONFIG_HOME=~/.config
export CL_HOME="$HOME/projects/cloudlock"
export PATH=$PATH:$CL_HOME/scripts

## Virtual env exports
export WORKON_HOME=~/.virtualenvs
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python2
export VIRTUALENVWRAPPER_VIRTUALENV=/usr/bin/virtualenv
export PROJECT_HOME=~/projects/

## Help psql find the dockerized postgres instance
export PGHOST="127.0.0.1"
export PGUSER="postgres"


## Increase ansible dynamic hosts cache
export CL_EC2_CACHE_MAX_AGE=60000

eval $(keychain --eval --noask --quiet id_rsa Common.pem)

# Source files
source ~/.bin/tmuxinator.zsh
source /usr/bin/virtualenvwrapper_lazy.sh
