# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

source $HOME/.config/my-configs/zsh/custom.zsh
source $HOME/.config/my-configs/zsh/bluevine.zsh
